version: 1.0.{build}
branches:
  only:
  - master
  - release
image: Visual Studio 2017
configuration: Debug
platform: Any CPU
build:
  project: UKSF-Launcher.sln
  verbosity: minimal
deploy:
- provider: WebDeploy
  server: www.uk-sf.com
  website: www.uk-sf.com
  username: uksf
  password:
    secure: Hl55QmaN/WLKIwjd1uYzFA==
  on:
    branch: release