version: "1.0.0.{build}"
environment:
  COVERALLS_REPO_TOKEN:
    secure: 3fEK++DqcBYsFmUUVtJ3keqDdrtJ3p8CFaLIWw70SloLgqDSi6DSDgr5fMF1Yke0
branches:
  only:
  - master
  - release
image: Visual Studio 2017
configuration: Debug
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3
before_build:
  - nuget restore
build:
  project: UKSF-Launcher.sln
  verbosity: minimal
test_script:
- cmd: >-
    cd C:\projects\launcher

    packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -returntargetcode -filter:"+[UKSF-Launcher*]* -[UKSF-Launcher.Tests]* -[UKSF-Launcher]UKSF_Launcher.UI.* -[UKSF-Launcher]UKSF_Launcher.Global -[UKSF-Launcher]UKSF_Launcher.Core -[UKSF-Launcher]UKSF_Launcher.Properties.*" -excludebyattribute:*.ExcludeFromCoverageAttribute "-target:tests.bat" -output:coverage.xml

    packages\coveralls.net.0.7.0\tools\csmacnz.Coveralls.exe --opencover -i coverage.xml
artifacts:
  - path: release\UKSF-Launcher.exe
    name: UKSF-Launcher
  - path: release\Updater.exe
    name: Updater
  - path: release\VersionUpdater.exe
    name: VersionUpdater
deploy:
- provider: FTP
  host: ftp.uk-sf.com
  protocol: ftp
  username: main
  password:
    secure: 1k1dPMXwKdh+kVVv5GxYyA==
  folder: /wamp/www/uksfnew/public/launcher
  artifact: UKSF-Launcher,Updater,VersionUpdater
  on:
    branch: release
after_deploy:
- cmd: '%APPVEYOR_BUILD_FOLDER%\release\PostDeployment.exe'
