version: 1.0.0.{build}
branches:
  only:
  - release
image: Visual Studio 2017
configuration: Debug
platform: Any CPU
build:
  project: UKSF-Launcher.sln
  verbosity: minimal
after_build:
- cmd: 7z a UKSF-Launcher.zip %APPVEYOR_BUILD_FOLDER%\bin\Debug\UKSF-Launcher.exe
deploy:
- provider: FTP
  host: uk-sf.com
  protocol: ftp
  username: main
  password:
    secure: 1k1dPMXwKdh+kVVv5GxYyA==
  folder: /wamp/www/uksfnew/public/launcher
  application: UKSF-Launcher.zip
  on:
    branch: release