version: "1.0.0.{build}"
environment:
  COVERALLS_REPO_TOKEN:
    secure: bIg0bHabZSbRpu6KG/YPae8nrv1Gd1gOYRyJrFJiQGAcNK2YUFNBgeYltICJs77M
branches:
  only:
  - master
  - release
image: Visual Studio 2017
configuration: Release
platform: x64
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: ':::'
cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'
  - '%LocalAppData%\NuGet\v3-cache'
before_build:
  - nuget restore
build:
  project: UKSF-Launcher.sln
  verbosity: minimal
test_script:
- cmd: >-
    cd C:\projects\launcher

    packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -returntargetcode -filter:"+[Launcher*]* -[Launcher.Tests]* -[Launcher]UKSF_Launcher.UI.* -[Launcher]UKSF_Launcher.Global -[Launcher]UKSF_Launcher.Core -[Launcher]UKSF_Launcher.Properties.*" -excludebyattribute:*.ExcludeFromCoverageAttribute "-target:tests.bat" -output:coverage.xml

    packages\coveralls.net.0.7.0\tools\csmacnz.Coveralls.exe --opencover -i coverage.xml
artifacts:
  - path: release\Setup.msi
    name: Setup
  - path: release\Launcher.exe
    name: Launcher
  - path: release\Patching.dll
    name: Patching
  - path: release\Network.dll
    name: Network
  - path: release\FastRsync.exe
    name: FastRsync
  - path: release\Updater.exe
    name: Updater
  - path: release\VersionUpdater.exe
    name: VersionUpdater
  - path: release\ServerService.exe
    name: ServerService
deploy:
- provider: FTP
  host: ftp.uk-sf.com
  protocol: ftp
  username: main
  password:
    secure: 1k1dPMXwKdh+kVVv5GxYyA==
  folder: /wamp/www/uksfnew/public/launcher
  artifact: Setup,Launcher,Patching,Network,FastRsync,Updater,VersionUpdater,ServerService
  on:
    branch: release
after_deploy:
- cmd: '%APPVEYOR_BUILD_FOLDER%\release\PostDeployment.exe'
